

cd /mnt/cephfs/home/yangyifan/yangyifan/code/learnToSyLf/Ha-NeRF; conda activate HaNeRF;  CUDA_VISIBLE_DEVICES=7,6,5,1 python train_mask_grid_sample.py   --root_dir /mnt/cephfs/dataset/NVS/nerfInWild/brandenburg_gate/ --dataset_name phototourism   --save_dir /mnt/cephfs/dataset/NVS/nerfInWild/experimental_results  --img_downscale 2 --use_cache   --N_importance 64 --N_samples 16   --num_epochs 20 --batch_size 1024   --optimizer adam --lr 5e-4 --lr_scheduler cosine   --exp_name gnerf_mpi_decoder_esrgan   --N_emb_xyz 15 --N_vocab 1500   --maskrs_max 5e-2 --maskrs_min 6e-3 --maskrs_k 1e-3 --maskrd 0   --N_a 48 --weightKL 1e-5 --weightRecA 1e-3 --weightMS 1e-6   --num_gpus 4 --chunk 131072 

##todo activation function
cd /mnt/cephfs/home/yangyifan/yangyifan/code/learnToSyLf/Ha-NeRF; conda activate HaNeRF;  CUDA_VISIBLE_DEVICES=0,2 python train_mask_grid_sample.py   --root_dir /mnt/cephfs/dataset/NVS/nerfInWild/brandenburg_gate/ --dataset_name phototourism   --save_dir /mnt/cephfs/dataset/NVS/nerfInWild/experimental_results  --img_downscale 2 --use_cache   --N_importance 64 --N_samples 64   --num_epochs 20 --batch_size 1024   --optimizer adam --lr 5e-4 --lr_scheduler cosine   --exp_name gnerf_mpi_decoder_activation_sigmiod   --N_emb_xyz 15 --N_vocab 1500   --maskrs_max 5e-2 --maskrs_min 6e-3 --maskrs_k 1e-3 --maskrd 0   --N_a 48 --weightKL 1e-5 --weightRecA 1e-3 --weightMS 1e-6   --num_gpus 2 --chunk 131072 

##todo activation function tanh
cd /mnt/cephfs/home/yangyifan/yangyifan/code/learnToSyLf/Ha-NeRF; conda activate HaNeRF;  CUDA_VISIBLE_DEVICES=1,3,4,5 python train_mask_grid_sample.py   --root_dir /mnt/cephfs/dataset/NVS/nerfInWild/brandenburg_gate/ --dataset_name phototourism   --save_dir /mnt/cephfs/dataset/NVS/nerfInWild/experimental_results  --img_downscale 2 --use_cache   --N_importance 64 --N_samples 64   --num_epochs 20 --batch_size 1024   --optimizer adam --lr 5e-4 --lr_scheduler cosine   --exp_name gnerf_mpi_decoder_activation_tanh    --N_emb_xyz 15 --N_vocab 1500   --maskrs_max 5e-2 --maskrs_min 6e-3 --maskrs_k 1e-3 --maskrd 0   --N_a 48 --weightKL 1e-5 --weightRecA 1e-3 --weightMS 1e-6   --num_gpus 4 --chunk 131072 

##todo esrgan
cd /mnt/cephfs/home/yangyifan/yangyifan/code/learnToSyLf/Ha-NeRF; conda activate HaNeRF;  CUDA_VISIBLE_DEVICES=1,3,4,0 python train_mask_grid_sample.py   --root_dir /mnt/cephfs/dataset/NVS/nerfInWild/brandenburg_gate/ --dataset_name phototourism   --save_dir /mnt/cephfs/dataset/NVS/nerfInWild/experimental_results  --img_downscale 2 --use_cache   --N_importance 64 --N_samples 16   --num_epochs 20 --batch_size 1024   --optimizer adam --lr 5e-4 --lr_scheduler cosine   --exp_name gnerf_mpi_decoder_esrgan   --N_emb_xyz 15 --N_vocab 1500   --maskrs_max 5e-2 --maskrs_min 6e-3 --maskrs_k 1e-3 --maskrd 0   --N_a 48 --weightKL 1e-5 --weightRecA 1e-3 --weightMS 1e-6   --num_gpus 4 --chunk 131072 

cd /mnt/cephfs/home/yangyifan/yangyifan/code/learnToSyLf/Ha-NeRF; conda activate HaNeRF;  CUDA_VISIBLE_DEVICES=0,1,2,6 python train_mask_grid_sample.py   --root_dir /mnt/cephfs/dataset/NVS/nerfInWild/brandenburg_gate/ --dataset_name phototourism   --save_dir /mnt/cephfs/dataset/NVS/nerfInWild/experimental_results  --img_downscale 2 --use_cache   --N_importance 64 --N_samples 16   --num_epochs 20 --batch_size 1024   --optimizer adam --lr 5e-4 --lr_scheduler cosine   --exp_name debug   --N_emb_xyz 15 --N_vocab 1500   --maskrs_max 5e-2 --maskrs_min 6e-3 --maskrs_k 1e-3 --maskrd 0   --N_a 48 --weightKL 1e-5 --weightRecA 1e-3 --weightMS 1e-6   --num_gpus 4 --chunk 131072 


###/mnt/cephfs/home/yangyifan/miniconda/envs/HaNeRF/bin/pip  install <pakage>
## feature volume render
cd /mnt/cephfs/home/yangyifan/yangyifan/code/learnToSyLf/Ha-NeRF; conda activate HaNeRF;  CUDA_VISIBLE_DEVICES=3,1 python train_mask_grid_sample.py   --root_dir /mnt/cephfs/dataset/NVS/nerfInWild/brandenburg_gate/ --dataset_name phototourism   --save_dir /mnt/cephfs/dataset/NVS/nerfInWild/experimental_results  --img_downscale 2 --use_cache   --N_importance 64 --N_samples 64   --num_epochs 20 --batch_size 1024   --optimizer adam --lr 5e-4 --lr_scheduler cosine   --exp_name gnerf_feature_volume_rendering_perturb00001_nerfout16 --N_emb_xyz 15 --N_vocab 1500   --maskrs_max 5e-2 --maskrs_min 6e-3 --maskrs_k 1e-3 --maskrd 0   --N_a 48 --weightKL 1e-5 --weightRecA 1e-3 --weightMS 1e-6   --num_gpus 2 --chunk 131072  --nerf_out_dim 32 --proj_name gnerf
--pertubeCord

####debug###
cd /mnt/cephfs/home/yangyifan/yangyifan/code/learnToSyLf/Ha-NeRF; conda activate HaNeRF;  CUDA_VISIBLE_DEVICES=4,5 python train_mask_grid_sample.py   --root_dir /mnt/cephfs/dataset/NVS/nerfInWild/brandenburg_gate/ --dataset_name phototourism   --save_dir /mnt/cephfs/dataset/NVS/nerfInWild/experimental_results  --img_downscale 2 --use_cache   --N_importance 64 --N_samples 64   --num_epochs 20 --batch_size 1024   --optimizer adam --lr 5e-4 --lr_scheduler cosine   --exp_name gnerf_fvr_baseline_no_perturb64 --N_emb_xyz 15 --N_vocab 1500   --maskrs_max 5e-2 --maskrs_min 6e-3 --maskrs_k 1e-3 --maskrd 0   --N_a 48 --weightKL 1e-5 --weightRecA 1e-3 --weightMS 1e-6   --num_gpus 2 --chunk 131072  --nerf_out_dim 64 --proj_name gnerf 

#20220920
